Repository Uma-Tech/parrot, pull requests merged in 2020-11, with the labels that each got.

#61 Secret key must be unique and secret for every installation.
  .github/workflows/tests.yml
  parrot/settings.py
Labels: security

#60 Adds reading environment from the .env file (handy for local developm…
  parrot/settings.py
Labels: enhancement

#67 issue-66: Adds default SECRET_KEY
  deploy/app/Dockerfile
Labels: bug
