Repository Uma-Tech/parrot, pull requests merged in 2020-12, with the labels that each got.

#74 Adds django-extensions and ipython for ease of development.
  parrot/settings.py
  parrot/urls.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#75 Fixes enormously long page loading time caused by loading all possibl…
  http_stubs/admin.py
Labels: enhancement

#79 Fixes issue with Vue breaking on log entries resembling mustache temp…
  templates/admin/home.html
Labels: bug

#46 #17 display header in column
  http_stubs/admin.py
  http_stubs/templatetags/stub_tags.py
  http_stubs/tests/test_tags.py
  templates/admin/http_stubs/httpstub/change_form.html
  templates/admin/http_stubs/includes/fieldset.html
  templates/admin/http_stubs/includes/fieldset_http_stub.html
  templates/admin/http_stubs/includes/fieldset_log_entry.html
  templates/admin/http_stubs/logentry/change_form.html
Labels: hacktoberfest-accepted

#78 issue-77: Fix absolute request url in HttpStubAdmin with regex(#77)
  http_stubs/templatetags/stub_tags.py
  http_stubs/tests/test_tags.py
  templates/admin/http_stubs/includes/fieldset_http_stub.html
Labels: bug

#85 Improves deploy
  .gitignore
  Makefile
  deploy/docker-compose.db.yml
  deploy/docker-compose.yml
Labels: enhancement

#70 Custom script for each request
  .isort.cfg
  Makefile
  README.md
  conftest.py
  deploy/docker-compose.db.yml
  deploy/docker-compose.develop.yml
  deploy/docker-compose.yml
  http_stubs/admin.py
  http_stubs/migrations/0005_httpstub_request_script_logentry_result_script.py
  http_stubs/models.py
  http_stubs/tasks.py
  http_stubs/templatetags/stub_tags.py
  http_stubs/tests/fixtures.py
  http_stubs/tests/test_tags.py
  http_stubs/tests/test_tasks.py
  http_stubs/tests/test_views.py
  http_stubs/views.py
  parrot/__init__.py
  parrot/celery.py
  parrot/settings.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#90 Fixes lgtm alert
  http_stubs/templatetags/stub_tags.py
Labels: enhancement
